### ISSUE TITLE
About '--Inverse'

### ISSUE THREAD

**Issue by NoBugNoErrorNoWarning** [thuml/Large-Time-Series-Model#31]
Thanks for your great work! I want to compare the inverse output data with origin data. But once I added '--inverse' to 'ECL.sh', an error occurred. 'ValueError: Found array with dim 3. None expected <= 2.'。 What should be done about it?
Traceback (most recent call last):
  File "/mnt/sdb1/Timer/Large-Time-Series-Model-main/run.py", line 179, in <module>
    exp.test(setting)
  File "/mnt/sdb1/Timer/Large-Time-Series-Model-main/exp/exp_forecast.py", line 252, in test
    outputs = test_data.inverse_transform(outputs.squeeze(0)).reshape(shape)
  File "/mnt/sdb1/Timer/Large-Time-Series-Model-main/data_provider/data_loader_benchmark.py", line 150, in inverse_transform
    return self.scaler.inverse_transform(data)
  File "/mnt/sdb1/miniconda3/envs/Timer/lib/python3.10/site-packages/sklearn/preprocessing/_data.py", line 1034, in inverse_transform
    X = check_array(
  File "/mnt/sdb1/miniconda3/envs/Timer/lib/python3.10/site-packages/sklearn/utils/validation.py", line 915, in check_array
    raise ValueError(
ValueError: Found array with dim 3. None expected <= 2.

**Comment by WenWeiTHU** [comment]
Hello, I think this should be the problem of incompatible dataset dimension. Could yo provide more information for us to help you correct this problem>
